<?php 
return [
    'path' => '',
    'remove_on_build' => ['cache','build'],
    'excludes' => [
        'bacon',
        'dasprid',
        'league',
        'paragonie',
        'spomky-labs',
        'phpseclib',
        'parsedown',
        'phpplot',
        'collection',
        'oaipmh',
        'ezyang',
        'phpoffice',
        'sphinx',
        'symfony',
        'mysqldump-php',
        'csrf',
        'lang',
        'guzzlehttp',
        'uuid',
        'nesbot',
        'marc',
        'zend',
        'recaptcha',
        'phpbarcode',
        'PHPMailer',
        'markbaker',
        'maennchen',
        'math',
        'flex',
        'psr',
        'myclabs',
        'Zend'
    ]
];
